package be.ac.fundp.uimanager.client.soap.implementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T15:20:13.410+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebServiceClient(name = "UI-Client", 
                  wsdlLocation = "http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl",
                  targetNamespace = "http://webApp.fundp.ac.be") 
public class UIClient_Service extends Service {

    /** The Constant WSDL_LOCATION. */
    public final static URL WSDL_LOCATION;

    /** The Constant SERVICE. */
    public final static QName SERVICE = new QName("http://webApp.fundp.ac.be", "UI-Client");
    
    /** The Constant UIClientSOAP. */
    public final static QName UIClientSOAP = new QName("http://webApp.fundp.ac.be", "UI-ClientSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UIClient_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new uI client_ service.
     *
     * @param wsdlLocation the wsdl location
     */
    public UIClient_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     * Instantiates a new uI client_ service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public UIClient_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new uI client_ service.
     */
    public UIClient_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * Gets the uI client soap.
     *
     * @return the uI client soap
     * returns UIClient
     */
    @WebEndpoint(name = "UI-ClientSOAP")
    public UIClient getUIClientSOAP() {
        return super.getPort(UIClientSOAP, UIClient.class);
    }

    /**
     * Gets the uI client soap.
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return the uI client soap
     * returns UIClient
     */
    @WebEndpoint(name = "UI-ClientSOAP")
    public UIClient getUIClientSOAP(WebServiceFeature... features) {
        return super.getPort(UIClientSOAP, UIClient.class, features);
    }

}
