//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//


package be.ac.fundp.precise.processDeployment.auiDeployment.codeGenerator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



/**
 * 
 * 				Is related to State by two relationships meaning that a transition has source state and a
 * 				target state. Additionally it is related to EventExpression and ActionExpression
 * 			
 * 
 * <p>Java class for Transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="transitionExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="event" type="{http://UsiXML-XSD/AbstractUIModel}EventExpression"/>
 *         &lt;element name="action" type="{http://UsiXML-XSD/AbstractUIModel}ActionExpression"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://UsiXML-XSD/AbstractUIModel",
		 name = "Transition", propOrder = {

})
public class Transition {

	/** The transition expression. */
	@XmlElement(namespace = "http://UsiXML-XSD/AbstractUIModel",required = true)
    protected String transitionExpression;
    
    /** The event. */
    @XmlElement(namespace = "http://UsiXML-XSD/AbstractUIModel",required = true)
    protected EventExpression event;
    
    /** The action. */
    @XmlElement(namespace = "http://UsiXML-XSD/AbstractUIModel",required = true)
    protected ActionExpression action;

    /**
     * Gets the value of the transitionExpression property.
     *
     * @return the transition expression
     * possible object is
     * {@link String }
     */
    public String getTransitionExpression() {
        return transitionExpression;
    }

    /**
     * Sets the value of the transitionExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransitionExpression(String value) {
        this.transitionExpression = value;
    }

    /**
     * Gets the value of the event property.
     *
     * @return the event
     * possible object is
     * {@link EventExpression }
     */
    public EventExpression getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventExpression }
     *     
     */
    public void setEvent(EventExpression value) {
        this.event = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return the action
     * possible object is
     * {@link ActionExpression }
     */
    public ActionExpression getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionExpression }
     *     
     */
    public void setAction(ActionExpression value) {
        this.action = value;
    }

}
