//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//


package be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Composition of one or several AbstractInteractionUnit
 * 			
 * 
 * <p>Java class for AbstractCompoundIU complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractCompoundIU">
 *   &lt;complexContent>
 *     &lt;extension base="{http://UsiXML-XSD/AbstractUIModel}AbstractInteractionUnit">
 *       &lt;sequence>
 *         &lt;element name="abstractInteractionUnit" type="{http://UsiXML-XSD/AbstractUIModel}AbstractInteractionUnit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://UsiXML-XSD/AbstractUIModel",
         name = "AbstractCompoundIU", propOrder = {
    "abstractInteractionUnit"
})
@XmlSeeAlso({
    AbstractSelectionIU.class
})
public class AbstractCompoundIU
    extends AbstractInteractionUnit
{

	@XmlElement(namespace = "http://UsiXML-XSD/AbstractUIModel",required = true)
    protected List<AbstractInteractionUnit> abstractInteractionUnit;

    /**
     * Gets the value of the abstractInteractionUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractInteractionUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractInteractionUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractInteractionUnit }
     * 
     * 
     */
    public List<AbstractInteractionUnit> getAbstractInteractionUnit() {
        if (abstractInteractionUnit == null) {
            abstractInteractionUnit = new ArrayList<AbstractInteractionUnit>();
        }
        return this.abstractInteractionUnit;
    }

}
