//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 03:49:22 PM CET 
//


package be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link AbstractTriggerIU }
     * 
     */
    public AbstractTriggerIU createAbstractTriggerIU() {
        return new AbstractTriggerIU();
    }

    /**
     * Create an instance of {@link AbstractLocalization }
     * 
     */
    public AbstractLocalization createAbstractLocalization() {
        return new AbstractLocalization();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link AbstractElementaryIU }
     * 
     */
    public AbstractElementaryIU createAbstractElementaryIU() {
        return new AbstractElementaryIU();
    }

    /**
     * Create an instance of {@link EventExpression }
     * 
     */
    public EventExpression createEventExpression() {
        return new EventExpression();
    }

    /**
     * Create an instance of {@link AbstractUIModel }
     * 
     */
    public AbstractUIModel createAbstractUIModel() {
        return new AbstractUIModel();
    }

    /**
     * Create an instance of {@link AbstractCompoundIU }
     * 
     */
    public AbstractCompoundIU createAbstractCompoundIU() {
        return new AbstractCompoundIU();
    }

    /**
     * Create an instance of {@link AbstractSelectionIU }
     * 
     */
    public AbstractSelectionIU createAbstractSelectionIU() {
        return new AbstractSelectionIU();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link Justification }
     * 
     */
    public Justification createJustification() {
        return new Justification();
    }

    /**
     * Create an instance of {@link AtomicAction }
     * 
     */
    public AtomicAction createAtomicAction() {
        return new AtomicAction();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link AbstractDataIU }
     * 
     */
    public AbstractDataIU createAbstractDataIU() {
        return new AbstractDataIU();
    }

    /**
     * Create an instance of {@link AbstractInteractionUnit }
     * 
     */
    public AbstractInteractionUnit createAbstractInteractionUnit() {
        return new AbstractInteractionUnit();
    }

    /**
     * Create an instance of {@link ActionExpression }
     * 
     */
    public ActionExpression createActionExpression() {
        return new ActionExpression();
    }

    /**
     * Create an instance of {@link TemporalEventExpression }
     * 
     */
    public TemporalEventExpression createTemporalEventExpression() {
        return new TemporalEventExpression();
    }

    /**
     * Create an instance of {@link TemporalActionExpression }
     * 
     */
    public TemporalActionExpression createTemporalActionExpression() {
        return new TemporalActionExpression();
    }

    /**
     * Create an instance of {@link AbstractListener }
     * 
     */
    public AbstractListener createAbstractListener() {
        return new AbstractListener();
    }

    /**
     * Create an instance of {@link AtomicEvent }
     * 
     */
    public AtomicEvent createAtomicEvent() {
        return new AtomicEvent();
    }

}
