//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 03:49:22 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://UsiXML-XSD/AbstractUIModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml;
