//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//

@XmlSchema (xmlns = {
		         @XmlNs(prefix = "usi", namespaceURI="http://UsiXML-XSD/AbstractUIModel"),
		         @XmlNs(prefix = "xsd", namespaceURI="http://www.w3.org2001XMLSchema")
		   },
		   namespace = "http://UsiXML-XSD/AbstractUIModel",
		   elementFormDefault = XmlNsForm.UNQUALIFIED
		)
package be.ac.fundp.precise.ui_bpel.ui.transformation.aui.serialization.xml;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

