package be.ac.fundp.uimanager.soapServer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-03-21T16:24:13.324+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "UiManager", 
                  wsdlLocation = "http://localhost:8090/UiManager/services/UiManagerSOAP?wsdl",
                  targetNamespace = "http://fundp.ac.be/UiManager/") 
public class UiManager_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fundp.ac.be/UiManager/", "UiManager");
    public final static QName UiManagerSOAP = new QName("http://fundp.ac.be/UiManager/", "UiManagerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/UiManager/services/UiManagerSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UiManager_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/UiManager/services/UiManagerSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UiManager_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UiManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UiManager_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UiManager
     */
    @WebEndpoint(name = "UiManagerSOAP")
    public UiManager getUiManagerSOAP() {
        return super.getPort(UiManagerSOAP, UiManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UiManager
     */
    @WebEndpoint(name = "UiManagerSOAP")
    public UiManager getUiManagerSOAP(WebServiceFeature... features) {
        return super.getPort(UiManagerSOAP, UiManager.class, features);
    }

}
