package be.ac.fundp.uimanager.userevent;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T20:30:13.098+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebServiceClient(name = "ManageUserEvent", 
                  wsdlLocation = "http://www.example.org/?wsdl",
                  targetNamespace = "http://fundp.ac.be/ManageUserEvent/") 
public class ManageUserEvent_Service extends Service {

    /** The Constant WSDL_LOCATION. */
    public final static URL WSDL_LOCATION;

    /** The Constant SERVICE. */
    public final static QName SERVICE = new QName("http://fundp.ac.be/ManageUserEvent/", "ManageUserEvent");
    
    /** The Constant ManageUserEventSOAP. */
    public final static QName ManageUserEventSOAP = new QName("http://fundp.ac.be/ManageUserEvent/", "ManageUserEventSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://www.example.org/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageUserEvent_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.example.org/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new manage user event_ service.
     *
     * @param wsdlLocation the wsdl location
     */
    public ManageUserEvent_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     * Instantiates a new manage user event_ service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public ManageUserEvent_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new manage user event_ service.
     */
    public ManageUserEvent_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * Gets the manage user event soap.
     *
     * @return the manage user event soap
     * returns ManageUserEvent
     */
    @WebEndpoint(name = "ManageUserEventSOAP")
    public ManageUserEvent getManageUserEventSOAP() {
        return super.getPort(ManageUserEventSOAP, ManageUserEvent.class);
    }

    /**
     * Gets the manage user event soap.
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return the manage user event soap
     * returns ManageUserEvent
     */
    @WebEndpoint(name = "ManageUserEventSOAP")
    public ManageUserEvent getManageUserEventSOAP(WebServiceFeature... features) {
        return super.getPort(ManageUserEventSOAP, ManageUserEvent.class, features);
    }

}
