package be.ac.fundp.uimanager.soapServer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-03-21T16:24:13.311+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://fundp.ac.be/UiManager/", name = "UiManager")
@XmlSeeAlso({ObjectFactory.class})
public interface UiManager {

    @RequestWrapper(localName = "inputOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.InputOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/inputOperation")
    @ResponseWrapper(localName = "inputOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.InputOperationResponse")
    public void inputOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(mode = WebParam.Mode.OUT, name = "data", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<be.ac.fundp.uimanager.soapServer.UiDataType>> data
    );

    @RequestWrapper(localName = "selectionOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.SelectionOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/selectionOperation")
    @ResponseWrapper(localName = "selectionOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.SelectionOperationResponse")
    public void selectionOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "data", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<be.ac.fundp.uimanager.soapServer.UiDataType>> data
    );

    @RequestWrapper(localName = "outputOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.OutputOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/outputOperation")
    @ResponseWrapper(localName = "outputOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.OutputOperationResponse")
    public void outputOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(name = "data", targetNamespace = "")
        java.util.List<be.ac.fundp.uimanager.soapServer.UiDataType> data
    );

    @WebResult(name = "processId", targetNamespace = "")
    @RequestWrapper(localName = "generateProcessId", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.GenerateProcessId")
    @WebMethod(action = "http://fundp.ac.be/UiManager/generateProcessId")
    @ResponseWrapper(localName = "generateProcessIdResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.GenerateProcessIdResponse")
    public java.lang.String generateProcessId();

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "pendingActions", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.PendingActions")
    @WebMethod(action = "http://fundp.ac.be/UiManager/pendingActions")
    @ResponseWrapper(localName = "pendingActionsResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.PendingActionsResponse")
    public java.util.List<be.ac.fundp.uimanager.soapServer.PendingInteraction> pendingActions(
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role
    );

    @Oneway
    @RequestWrapper(localName = "registryRole", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.uimanager.soapServer.RegistryRole")
    @WebMethod(action = "http://fundp.ac.be/UiManager/registryRole")
    public void registryRole(
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role,
        @WebParam(name = "host", targetNamespace = "")
        java.lang.String host
    );
}
