package be.ac.fundp.precise.processMediation.dataInteraction.webService;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-04-26T17:23:14.016+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://precise.fundp.ac.be/UserEventListener/", name = "UserEventListener")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEventListener {

    @Oneway
    @RequestWrapper(localName = "fireEvent", targetNamespace = "http://precise.fundp.ac.be/UserEventListener/", className = "be.ac.fundp.precise.processMediation.dataInteraction.webService.FireEvent")
    @WebMethod(action = "http://precise.fundp.ac.be/UserEventListener/fireEvent")
    public void fireEvent(
        @WebParam(name = "eventId", targetNamespace = "")
        java.lang.String eventId,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );
}
