package org.example.partnerws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T18:22:36.032+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "partnerWS", 
                  wsdlLocation = "http://www.example.org/?wsdl",
                  targetNamespace = "http://www.example.org/partnerWS/") 
public class PartnerWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/partnerWS/", "partnerWS");
    public final static QName PartnerWSSOAP = new QName("http://www.example.org/partnerWS/", "partnerWSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://www.example.org/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartnerWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.example.org/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PartnerWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartnerWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PartnerWS
     */
    @WebEndpoint(name = "partnerWSSOAP")
    public PartnerWS getPartnerWSSOAP() {
        return super.getPort(PartnerWSSOAP, PartnerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartnerWS
     */
    @WebEndpoint(name = "partnerWSSOAP")
    public PartnerWS getPartnerWSSOAP(WebServiceFeature... features) {
        return super.getPort(PartnerWSSOAP, PartnerWS.class, features);
    }

}
