package be.ac.fundp.uimanager.userevent.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T20:38:12.395+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebService(targetNamespace = "http://precise.fundp.ac.be/UserEventListener/", name = "UserEventListnerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEventListnerPortType {

    /**
     * Fire event.
     *
     * @param eventId the event id
     * @param processId the process id
     */
    @Oneway
    @Action(input = "//precise.fundp.ac.be/UserEventListener/fireEvent")
    @RequestWrapper(localName = "fireEvent", targetNamespace = "http://precise.fundp.ac.be/UserEventListener/", className = "be.ac.fundp.uimanager.userevent.client.FireEvent")
    @WebMethod(action = "http://precise.fundp.ac.be/UserEventListener/fireEvent")
    public void fireEvent(
        @WebParam(name = "eventId", targetNamespace = "")
        java.lang.String eventId,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );
}
