
package be.ac.fundp.webapp.service.eventclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T21:07:43.264+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
public final class ManageUserEvent_ManageUserEventSOAP_Client {

    /** The Constant SERVICE_NAME. */
    private static final QName SERVICE_NAME = new QName("http://fundp.ac.be/ManageUserEvent/", "ManageUserEvent");

    /**
     * Instantiates a new manage user event_ manage user event soa p_ client.
     */
    private ManageUserEvent_ManageUserEventSOAP_Client() {
    }

    /**
     * The main method.
     *
     * @param args the arguments
     * @throws Exception the exception
     */
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ManageUserEvent_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ManageUserEvent_Service ss = new ManageUserEvent_Service(wsdlURL, SERVICE_NAME);
        ManageUserEvent port = ss.getManageUserEventSOAP();  
        
        {
        System.out.println("Invoking communicateUserEvent...");
        java.lang.String _communicateUserEvent_processId = "_communicateUserEvent_processId244106812";
        java.lang.String _communicateUserEvent_eventId = "_communicateUserEvent_eventId1448145039";
        java.lang.String _communicateUserEvent_role = "_communicateUserEvent_role-1025140882";
        port.communicateUserEvent(_communicateUserEvent_processId, _communicateUserEvent_eventId, _communicateUserEvent_role);


        }

        System.exit(0);
    }

}
