package be.ac.fundp.webapp.service.eventclient;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T21:07:43.471+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebService(targetNamespace = "http://fundp.ac.be/ManageUserEvent/", name = "ManageUserEvent")
@XmlSeeAlso({ObjectFactory.class})
public interface ManageUserEvent {

    /**
     * Communicate user event.
     *
     * @param processId the process id
     * @param eventId the event id
     * @param role the role
     */
    @Oneway
    @RequestWrapper(localName = "communicateUserEvent", targetNamespace = "http://fundp.ac.be/ManageUserEvent/", className = "be.ac.fundp.webapp.service.eventclient.CommunicateUserEvent")
    @WebMethod(action = "http://fundp.ac.be/ManageUserEvent/communicateUserEvent")
    public void communicateUserEvent(
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId,
        @WebParam(name = "eventId", targetNamespace = "")
        java.lang.String eventId,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role
    );
}
