
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.partnerws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T18:22:35.950+01:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "partnerWS",
                      portName = "partnerWSSOAP",
                      targetNamespace = "http://www.example.org/partnerWS/",
                      wsdlLocation = "http://www.example.org/?wsdl",
                      endpointInterface = "org.example.partnerws.PartnerWS")
                      
public class PartnerWSImpl implements PartnerWS {

    private static final Logger LOG = Logger.getLogger(PartnerWSImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.partnerws.PartnerWS#calculateDiscount(int  price ,)java.lang.String  product )*
     */
    public int calculateDiscount(int price,java.lang.String product) { 
        LOG.info("Executing operation calculateDiscount");
        
        return 100;

    }

    /* (non-Javadoc)
     * @see org.example.partnerws.PartnerWS#shipmentPrice(java.lang.String  shipper ,)java.lang.String  product )*
     */
    public int shipmentPrice(java.lang.String shipper,java.lang.String product) { 
        LOG.info("Executing operation shipmentPrice");
    
        return 50;
        
    }

    /* (non-Javadoc)
     * @see org.example.partnerws.PartnerWS#calculateInitialPrice(java.lang.String  product )*
     */
    public int calculateInitialPrice(java.lang.String product) { 
        LOG.info("Executing operation calculateInitialPrice");
        return 150;
        
    }

    /* (non-Javadoc)
     * @see org.example.partnerws.PartnerWS#calculatePrice(int  initialPrice ,)int  shipPrice ,)java.lang.String  product )*
     */
    public int calculatePrice(int initialPrice,int shipPrice,java.lang.String product) { 
        LOG.info("Executing operation calculatePrice");
        
        return 140;
    }

}
