<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://eclipse.org/bpel/bpel-ui/" nsPrefix="bpel-ui">
  <eClassifiers xsi:type="ecore:EClass" name="UserInteraction" abstract="true" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensionActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//UserRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRole" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOutputUI" eSuperTypes="#//UserInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVariable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataInputUI" eSuperTypes="#//UserInteraction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userValidation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputVariable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSelectionUI" eSuperTypes="#//DataInputUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionUI" eSuperTypes="#//UserInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choices" lowerBound="2"
        upperBound="-1" eType="#//Choice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="onDataInput" value="1"/>
    <eLiterals name="onDataOutput" value="2"/>
    <eLiterals name="onDataSelection" value="3" literal="onDataSelection"/>
    <eLiterals name="onDecisionInteraction" value="4"/>
    <eLiterals name="onImplicitInteracion" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnUserEvent" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userRole" eType="#//UserRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewPick" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensionActivity ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Pick">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInteracion" upperBound="-1"
        eType="#//OnUserEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEventHandler" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//EventHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInteracion" upperBound="-1"
        eType="#//OnUserEvent"/>
  </eClassifiers>
</ecore:EPackage>
