/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package be.ac.fundp.precise.processMediation.userEvent.service;

import java.util.List;
import java.util.logging.Logger;

import be.ac.fundp.precise.clientAppMediation.ClientAppMediationManager;
import be.ac.fundp.precise.dataManagment.CoordinatedData;
import be.ac.fundp.precise.dataManagment.DataManager;
import be.ac.fundp.precise.processMediation.userEvent.SoapServerUtil;

/**
 * This class was generated by Apache CXF 2.5.0 2012-06-20T11:39:42.671+02:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(serviceName = "UiManager", portName = "UiManagerSOAP", targetNamespace = "http://fundp.ac.be/UiManager/", wsdlLocation = "http://localhost:8050/UsiWSC_Manager/services/UiManagerSOAP?wsdl", endpointInterface = "be.ac.fundp.precise.processMediation.userEvent.service.UiManager")
public class UiManagerImpl implements UiManager {

	private static final Logger LOG = Logger.getLogger(UiManagerImpl.class
			.getName());

	private ClientAppMediationManager clientMediator = ClientAppMediationManager
			.getInstance();

	/*
	 * (non-Javadoc)
	 * 
	 * @see be.ac.fundp.precise.processMediation.userEvent.service.UiManager#
	 * inputOperation(java.lang.String userInteracId ,)java.lang.String role
	 * ,)java.lang.String processId
	 * ,)java.util.List<be.ac.fundp.precise.processMediation
	 * .userEvent.service.UiDataType> data )*
	 */
	public void inputOperation(
			javax.xml.ws.Holder<java.lang.String> userInteracId,
			javax.xml.ws.Holder<java.lang.String> role,
			javax.xml.ws.Holder<java.lang.String> processId,
			javax.xml.ws.Holder<java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType>> data) {
		LOG.info("Executing operation inputOperation");
		System.out.println("INPUTTTTTTTTT");
		System.out.println(userInteracId.value);
		System.out.println(role.value);
		System.out.println(processId.value);
		try {
			List<CoordinatedData> reponse = clientMediator
					.requireInputInteraction(role.value, processId.value,
							userInteracId.value);
			data.value = SoapServerUtil.providedData2UiDataType(reponse);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see be.ac.fundp.precise.processMediation.userEvent.service.UiManager#
	 * selectionOperation(java.lang.String userInteracId ,)java.lang.String role
	 * ,)java.lang.String processId
	 * ,)java.util.List<be.ac.fundp.precise.processMediation
	 * .userEvent.service.UiDataType> data )*
	 */
	public void selectionOperation(
			javax.xml.ws.Holder<java.lang.String> userInteracId,
			javax.xml.ws.Holder<java.lang.String> role,
			javax.xml.ws.Holder<java.lang.String> processId,
			javax.xml.ws.Holder<java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType>> data) {
		LOG.info("Executing operation selectionOperation");
		System.out.println(userInteracId.value);
		System.out.println(role.value);
		System.out.println(processId.value);
		System.out.println(data);
		try {
			List<CoordinatedData> reponse = clientMediator
					.requireSelectionInteracion(processId.value,
							userInteracId.value,
							SoapServerUtil.uiDataType2ProvidedData(data.value),
							role.value);
			data.value = SoapServerUtil.providedData2UiDataType(reponse);
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see be.ac.fundp.precise.processMediation.userEvent.service.UiManager#
	 * outputOperation(java.lang.String userInteracId ,)java.lang.String role
	 * ,)java.lang.String processId
	 * ,)java.util.List<be.ac.fundp.precise.processMediation
	 * .userEvent.service.UiDataType> data )*
	 */
	public void outputOperation(
			javax.xml.ws.Holder<java.lang.String> userInteracId,
			javax.xml.ws.Holder<java.lang.String> role,
			javax.xml.ws.Holder<java.lang.String> processId,
			java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType> data) {
		LOG.info("Executing operation outputOperation");
		System.out.println(userInteracId);
		System.out.println(role);
		System.out.println(processId);
		System.out.println(data);
		try {
			clientMediator.requireOutputInteracion(processId.value,
					userInteracId.value,
					SoapServerUtil.uiDataType2ProvidedData(data), role.value);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		System.out.println("Output Interaction DONE");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see be.ac.fundp.precise.processMediation.userEvent.service.UiManager#
	 * generateProcessId(java.lang.String processName )*
	 */
	public java.lang.String generateProcessId(java.lang.String processName) {
		LOG.info("Executing operation generateProcessId");
		System.out.println("GEEEENNNNN");
		try {
			return DataManager.idGen.genId();
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
