package be.ac.fundp.precise.processMediation.userEvent.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-06-20T11:39:42.755+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://fundp.ac.be/UiManager/", name = "UiManager")
@XmlSeeAlso({ObjectFactory.class})
public interface UiManager {

    @RequestWrapper(localName = "inputOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.InputOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/inputOperation")
    @ResponseWrapper(localName = "inputOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.InputOperationResponse")
    public void inputOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(mode = WebParam.Mode.OUT, name = "data", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType>> data
    );

    @RequestWrapper(localName = "selectionOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.SelectionOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/selectionOperation")
    @ResponseWrapper(localName = "selectionOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.SelectionOperationResponse")
    public void selectionOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "data", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType>> data
    );

    @RequestWrapper(localName = "outputOperation", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.OutputOperation")
    @WebMethod(action = "http://fundp.ac.be/UiManager/outputOperation")
    @ResponseWrapper(localName = "outputOperationResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.OutputOperationResponse")
    public void outputOperation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "userInteracId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> userInteracId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "role", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> role,
        @WebParam(mode = WebParam.Mode.INOUT, name = "processId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> processId,
        @WebParam(name = "data", targetNamespace = "")
        java.util.List<be.ac.fundp.precise.processMediation.userEvent.service.UiDataType> data
    );

    @WebResult(name = "processId", targetNamespace = "")
    @RequestWrapper(localName = "generateProcessId", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.GenerateProcessId")
    @WebMethod(action = "http://fundp.ac.be/UiManager/generateProcessId")
    @ResponseWrapper(localName = "generateProcessIdResponse", targetNamespace = "http://fundp.ac.be/UiManager/", className = "be.ac.fundp.precise.processMediation.userEvent.service.GenerateProcessIdResponse")
    public java.lang.String generateProcessId(
        @WebParam(name = "processName", targetNamespace = "")
        java.lang.String processName
    );
}
