
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package be.ac.fundp.precise.processMediation.startProcess.webService;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-06-19T16:43:51.830+02:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProcessOperations",
                      portName = "ProcessOperationsSOAP11port_http",
                      targetNamespace = "http://precise.fundp.ac.be/ProcessOperations/",
                      wsdlLocation = "http://localhost:8080/ode/processes/ProcessOperations?wsdl",
                      endpointInterface = "be.ac.fundp.precise.processMediation.startProcess.webService.ProcessOperationsPortType")
                      
public class ProcessOperationsPortTypeImpl implements ProcessOperationsPortType {

    private static final Logger LOG = Logger.getLogger(ProcessOperationsPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see be.ac.fundp.precise.processMediation.startProcess.webService.ProcessOperationsPortType#fireEvent(java.lang.String  eventId ,)java.lang.String  processId )*
     */
    public void fireEvent(java.lang.String eventId,java.lang.String processId) { 
        LOG.info("Executing operation fireEvent");
        System.out.println(eventId);
        System.out.println(processId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see be.ac.fundp.precise.processMediation.startProcess.webService.ProcessOperationsPortType#start(java.lang.String  processId ,)java.lang.String  processType )*
     */
    public void start(java.lang.String processId,java.lang.String processType) { 
        LOG.info("Executing operation start");
        System.out.println(processId);
        System.out.println(processType);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
