
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package be.ac.fundp.webapp.service.provider;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import be.ac.fundp.webapp.service.manager.UiManager;
import be.ac.fundp.webapp.service.representation.DataItem;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-18T15:25:02.268+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */

@javax.jws.WebService(
                      serviceName = "UI-Client",
                      portName = "UI-ClientSOAP",
                      targetNamespace = "http://webApp.fundp.ac.be",
                      wsdlLocation = "http://localhost:8050/WebBrowserAppClient/wsdl/UI-Client.wsdl",
                      endpointInterface = "be.ac.fundp.webapp.service.provider.UIClient")
                      
public class UIClientImpl implements UIClient {

    /** The Constant LOG. */
    private static final Logger LOG = Logger.getLogger(UIClientImpl.class.getName());
    
    /** The ui manager. */
    protected UiManager uiManager = UiManager.getInstance();
    
    /* (non-Javadoc)
     * @see be.ac.fundp.webapp.service.provider.UIClient#requireAssyncInteraction(java.lang.String, java.util.List, java.lang.String, java.lang.String)
     */
    public void requireAssyncInteraction(String cuiId,List<DataItemType> inputData,String role,String processId) { 
        LOG.info("Executing operation requireAssyncInteraction");
        System.out.println(cuiId);
        System.out.println(inputData);
        System.out.println(role);
        System.out.println(processId);
        uiManager.addUserInteraction(cuiId, role, processId, inputData);
    }

	/* (non-Javadoc)
	 * @see be.ac.fundp.webapp.service.provider.UIClient#requireSyncInteraction(java.lang.String, java.util.List, java.lang.String, java.lang.String)
	 */
	public List<DataItemType> requireSyncInteraction(String cuiId,List<DataItemType> inputData,String role,String processId) { 
        //LOG.info("Executing operation requireSyncInteraction");
        System.out.println(cuiId);
        System.out.println(inputData);
        System.out.println(role);
        System.out.println(processId);
        uiManager.addUserInteraction(cuiId, role, processId, inputData);
        try {
        	List<DataItem> dataSentBack = uiManager.waitDataFromUser(cuiId, role, processId);
            List<DataItemType> response = new ArrayList<DataItemType>();
            for (DataItem aDataItem : dataSentBack) {
            	 DataItemType aReturningDataType = new DataItemType();
                 aReturningDataType.setDataItemId(aDataItem.getDataItemId());
                 aReturningDataType.setTypeName(aDataItem.getType());
                 aReturningDataType.setData(aDataItem.getData());
                 response.add(aReturningDataType);
			}
            return response;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}