package be.ac.fundp.webapp.service.provider;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-18T15:25:02.590+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebService(targetNamespace = "http://webApp.fundp.ac.be", name = "UI-Client")
@XmlSeeAlso({ObjectFactory.class})
public interface UIClient {

    /**
     * Require assync interaction.
     *
     * @param cuiId the cui id
     * @param inputData the input data
     * @param role the role
     * @param processId the process id
     */
    @Oneway
    @RequestWrapper(localName = "requireAssyncInteraction", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.webapp.service.provider.RequireAssyncInteraction")
    @WebMethod(action = "http://webApp.fundp.ac.be/requireAssyncInteraction")
    public void requireAssyncInteraction(
        @WebParam(name = "cuiId", targetNamespace = "")
        java.lang.String cuiId,
        @WebParam(name = "inputData", targetNamespace = "")
        java.util.List<be.ac.fundp.webapp.service.provider.DataItemType> inputData,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );

    /**
     * Require sync interaction.
     *
     * @param cuiId the cui id
     * @param inputData the input data
     * @param role the role
     * @param processId the process id
     * @return the java.util. list
     */
    @WebResult(name = "outData", targetNamespace = "")
    @RequestWrapper(localName = "requireSyncInteraction", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.webapp.service.provider.RequireSyncInteraction")
    @WebMethod(action = "http://webApp.fundp.ac.be/NewOperation")
    @ResponseWrapper(localName = "requireSyncInteractionResponse", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.webapp.service.provider.RequireSyncInteractionResponse")
    public java.util.List<be.ac.fundp.webapp.service.provider.DataItemType> requireSyncInteraction(
        @WebParam(name = "cuiId", targetNamespace = "")
        java.lang.String cuiId,
        @WebParam(name = "inputData", targetNamespace = "")
        java.util.List<be.ac.fundp.webapp.service.provider.DataItemType> inputData,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );
}
