package be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-27T15:51:55.111+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://webApp.fundp.ac.be", name = "UI-Client")
@XmlSeeAlso({ObjectFactory.class})
public interface UIClient {

    @Oneway
    @RequestWrapper(localName = "requireAssyncInteraction", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.RequireAssyncInteraction")
    @WebMethod(action = "http://webApp.fundp.ac.be/requireAssyncInteraction")
    public void requireAssyncInteraction(
        @WebParam(name = "cuiId", targetNamespace = "")
        java.lang.String cuiId,
        @WebParam(name = "inputData", targetNamespace = "")
        java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> inputData,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );

    @WebResult(name = "outData", targetNamespace = "")
    @RequestWrapper(localName = "requireSyncInteraction", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.RequireSyncInteraction")
    @WebMethod(action = "http://webApp.fundp.ac.be/requireSyncInteraction")
    @ResponseWrapper(localName = "requireSyncInteractionResponse", targetNamespace = "http://webApp.fundp.ac.be", className = "be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.RequireSyncInteractionResponse")
    public java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> requireSyncInteraction(
        @WebParam(name = "cuiId", targetNamespace = "")
        java.lang.String cuiId,
        @WebParam(name = "inputData", targetNamespace = "")
        java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> inputData,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );
}
