
package be.ac.fundp.precise.processMediation.startProcess.webService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-06-19T16:43:51.760+02:00
 * Generated source version: 2.5.0
 * 
 */
public final class ProcessOperationsPortType_ProcessOperationsSOAP11PortHttp_Client {

    private static final QName SERVICE_NAME = new QName("http://precise.fundp.ac.be/ProcessOperations/", "ProcessOperations");

    private ProcessOperationsPortType_ProcessOperationsSOAP11PortHttp_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProcessOperations.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProcessOperations ss = new ProcessOperations(wsdlURL, SERVICE_NAME);
        ProcessOperationsPortType port = ss.getProcessOperationsSOAP11PortHttp();  
        
        {
        System.out.println("Invoking fireEvent...");
        java.lang.String _fireEvent_eventId = "_fireEvent_eventId404952721";
        java.lang.String _fireEvent_processId = "_fireEvent_processId86869150";
        port.fireEvent(_fireEvent_eventId, _fireEvent_processId);


        }
        {
        System.out.println("Invoking start...");
        java.lang.String _start_processId = "_start_processId-738189846";
        java.lang.String _start_processType = "_start_processType1050545032";
        port.start(_start_processId, _start_processType);


        }

        System.exit(0);
    }

}
