package be.ac.fundp.precise.processMediation.startProcess.webService;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-06-19T16:43:51.858+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://precise.fundp.ac.be/ProcessOperations/", name = "ProcessOperationsPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProcessOperationsPortType {

    @Oneway
    @Action(input = "//precise.fundp.ac.be/ProcessOperations/fireEvent")
    @RequestWrapper(localName = "fireEvent", targetNamespace = "http://precise.fundp.ac.be/ProcessOperations/", className = "be.ac.fundp.precise.processMediation.startProcess.webService.FireEvent")
    @WebMethod(action = "http://precise.fundp.ac.be/ProcessOperations/fireEvent")
    public void fireEvent(
        @WebParam(name = "eventId", targetNamespace = "")
        java.lang.String eventId,
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId
    );

    @Oneway
    @Action(input = "//precise.fundp.ac.be/ProcessOperations/start")
    @RequestWrapper(localName = "start", targetNamespace = "http://precise.fundp.ac.be/ProcessOperations/", className = "be.ac.fundp.precise.processMediation.startProcess.webService.Start")
    @WebMethod(action = "http://precise.fundp.ac.be/ProcessOperations/start")
    public void start(
        @WebParam(name = "processId", targetNamespace = "")
        java.lang.String processId,
        @WebParam(name = "processType", targetNamespace = "")
        java.lang.String processType
    );
}
