package be.ac.fundp.precise.processMediation.startProcess.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-06-19T16:43:51.867+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "ProcessOperations", 
                  wsdlLocation = "http://localhost:8080/ode/processes/ProcessOperations?wsdl",
                  targetNamespace = "http://precise.fundp.ac.be/ProcessOperations/") 
public class ProcessOperations extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://precise.fundp.ac.be/ProcessOperations/", "ProcessOperations");
    public final static QName ProcessOperationsSOAP11PortHttp = new QName("http://precise.fundp.ac.be/ProcessOperations/", "ProcessOperationsSOAP11port_http");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ode/processes/ProcessOperations?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessOperations.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ode/processes/ProcessOperations?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProcessOperations(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessOperations(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessOperations() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProcessOperationsPortType
     */
    @WebEndpoint(name = "ProcessOperationsSOAP11port_http")
    public ProcessOperationsPortType getProcessOperationsSOAP11PortHttp() {
        return super.getPort(ProcessOperationsSOAP11PortHttp, ProcessOperationsPortType.class);
    }
    
    /**
    *
    * @return
    *     returns ProcessOperationsPortType
    */
   @WebEndpoint(name = "ProcessOperationsSOAP11port_http")
   public ProcessOperationsPortType getProcessOperationsSOAP11PortHttp(String processName) {
	   QName ProcessOperationsSOAP11PortHttp = new QName("http://precise.fundp.ac.be/ProcessOperations/", "ProcessOperations"+processName+"SOAP11port_http");
       return super.getPort(ProcessOperationsSOAP11PortHttp, ProcessOperationsPortType.class);
   }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessOperationsPortType
     */
    @WebEndpoint(name = "ProcessOperationsSOAP11port_http")
    public ProcessOperationsPortType getProcessOperationsSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(ProcessOperationsSOAP11PortHttp, ProcessOperationsPortType.class, features);
    }

}
