package be.ac.fundp.uimanager.provider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-20T15:08:02.574+01:00
 * Generated source version: 2.5.0
 *
 * @author Waldemar Pires Ferreira Neto (waldemar.neto@fundp.ac.be)
 * @date Dec 9, 2011
 */
@WebServiceClient(name = "UiManager", 
                  wsdlLocation = "http://localhost:8090/UiManager/services/UiManager/?wsdl",
                  targetNamespace = "http://fundp.ac.be/UiManager/") 
public class UiManager_Service extends Service {

    /** The Constant WSDL_LOCATION. */
    public final static URL WSDL_LOCATION;

    /** The Constant SERVICE. */
    public final static QName SERVICE = new QName("http://fundp.ac.be/UiManager/", "UiManager");
    
    /** The Constant UiManagerSOAP. */
    public final static QName UiManagerSOAP = new QName("http://fundp.ac.be/UiManager/", "UiManagerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/UiManager/services/UiManager/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UiManager_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/UiManager/services/UiManager/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new ui manager_ service.
     *
     * @param wsdlLocation the wsdl location
     */
    public UiManager_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     * Instantiates a new ui manager_ service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public UiManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new ui manager_ service.
     */
    public UiManager_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * Gets the ui manager soap.
     *
     * @return the ui manager soap
     * returns UiManager
     */
    @WebEndpoint(name = "UiManagerSOAP")
    public UiManager getUiManagerSOAP() {
        return super.getPort(UiManagerSOAP, UiManager.class);
    }

    /**
     * Gets the ui manager soap.
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return the ui manager soap
     * returns UiManager
     */
    @WebEndpoint(name = "UiManagerSOAP")
    public UiManager getUiManagerSOAP(WebServiceFeature... features) {
        return super.getPort(UiManagerSOAP, UiManager.class, features);
    }

}
