package be.ac.fundp.precise.processDeployment.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-05-08T14:36:31.771+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "ProcessDeployerService", 
                  wsdlLocation = "http://localhost:8050/UsiWSC_Manager/services/ProcessDeployer?wsdl",
                  targetNamespace = "http://precise.funpd.ac.be/AuiDeployer") 
public class ProcessDeployerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://precise.funpd.ac.be/AuiDeployer", "ProcessDeployerService");
    public final static QName ProcessDeployer = new QName("http://precise.funpd.ac.be/AuiDeployer", "ProcessDeployer");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8050/UsiWSC_Manager/services/ProcessDeployer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessDeployerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8050/UsiWSC_Manager/services/ProcessDeployer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProcessDeployerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessDeployerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessDeployerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProcessDeployer
     */
    @WebEndpoint(name = "ProcessDeployer")
    public ProcessDeployer getProcessDeployer() {
        return super.getPort(ProcessDeployer, ProcessDeployer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessDeployer
     */
    @WebEndpoint(name = "ProcessDeployer")
    public ProcessDeployer getProcessDeployer(WebServiceFeature... features) {
        return super.getPort(ProcessDeployer, ProcessDeployer.class, features);
    }

}
