package be.ac.fundp.precise.processMediation.dataInteraction.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-04-26T17:23:14.024+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "UserEventListener", 
                  wsdlLocation = "http://localhost:8080/ode/processes/UserEventListner?wsdl",
                  targetNamespace = "http://precise.fundp.ac.be/UserEventListener/") 
public class UserEventListener_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://precise.fundp.ac.be/UserEventListener/", "UserEventListener");
    public final static QName UserEventListenerSOAP = new QName("http://precise.fundp.ac.be/UserEventListener/", "UserEventListenerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ode/processes/UserEventListner?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserEventListener_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ode/processes/UserEventListner?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserEventListener_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserEventListener_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserEventListener_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UserEventListener
     */
    @WebEndpoint(name = "UserEventListenerSOAP")
    public UserEventListener getUserEventListenerSOAP() {
        return super.getPort(UserEventListenerSOAP, UserEventListener.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserEventListener
     */
    @WebEndpoint(name = "UserEventListenerSOAP")
    public UserEventListener getUserEventListenerSOAP(WebServiceFeature... features) {
        return super.getPort(UserEventListenerSOAP, UserEventListener.class, features);
    }

}
