//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//


package be.ac.fundp.precise.processDeployment.auiDeployment.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemporalOperator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TemporalOperator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ENABLING"/>
 *     &lt;enumeration value="CHOICE"/>
 *     &lt;enumeration value="CONCURRENCY"/>
 *     &lt;enumeration value="SUSPEND"/>
 *     &lt;enumeration value="DISABLING"/>
 *     &lt;enumeration value="ORDERINDEPENDANCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(namespace = "http://UsiXML-XSD/AbstractUIModel",
		 name = "TemporalOperator")
@XmlEnum
public enum TemporalOperator {

    ENABLING,
    CHOICE,
    CONCURRENCY,
    SUSPEND,
    DISABLING,
    ORDERINDEPENDANCE;

    public String value() {
        return name();
    }

    public static TemporalOperator fromValue(String v) {
        return valueOf(v);
    }

}
