
package be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-27T15:51:55.013+01:00
 * Generated source version: 2.5.0
 * 
 */
public final class UIClient_UIClientSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://webApp.fundp.ac.be", "UI-Client");

    private UIClient_UIClientSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UIClient_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UIClient_Service ss = new UIClient_Service(wsdlURL, SERVICE_NAME);
        UIClient port = ss.getUIClientSOAP();  
        
        {
        System.out.println("Invoking requireAssyncInteraction...");
        java.lang.String _requireAssyncInteraction_cuiId = "_requireAssyncInteraction_cuiId1189109713";
        java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> _requireAssyncInteraction_inputData = new java.util.ArrayList<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType>();
        be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType _requireAssyncInteraction_inputDataVal1 = new be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType();
        _requireAssyncInteraction_inputDataVal1.setDataItemId("DataItemId49488813");
        _requireAssyncInteraction_inputDataVal1.setTypeName("TypeName-1903497430");
        java.lang.Object _requireAssyncInteraction_inputDataVal1Data = null;
        _requireAssyncInteraction_inputDataVal1.setData(_requireAssyncInteraction_inputDataVal1Data);
        _requireAssyncInteraction_inputData.add(_requireAssyncInteraction_inputDataVal1);
        java.lang.String _requireAssyncInteraction_role = "_requireAssyncInteraction_role-1668045195";
        java.lang.String _requireAssyncInteraction_processId = "_requireAssyncInteraction_processId2020481821";
        port.requireAssyncInteraction(_requireAssyncInteraction_cuiId, _requireAssyncInteraction_inputData, _requireAssyncInteraction_role, _requireAssyncInteraction_processId);


        }
        {
        System.out.println("Invoking requireSyncInteraction...");
        java.lang.String _requireSyncInteraction_cuiId = "_requireSyncInteraction_cuiId21532725";
        java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> _requireSyncInteraction_inputData = new java.util.ArrayList<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType>();
        be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType _requireSyncInteraction_inputDataVal1 = new be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType();
        _requireSyncInteraction_inputDataVal1.setDataItemId("DataItemId-183924132");
        _requireSyncInteraction_inputDataVal1.setTypeName("TypeName394394667");
        java.lang.Object _requireSyncInteraction_inputDataVal1Data = null;
        _requireSyncInteraction_inputDataVal1.setData(_requireSyncInteraction_inputDataVal1Data);
        _requireSyncInteraction_inputData.add(_requireSyncInteraction_inputDataVal1);
        java.lang.String _requireSyncInteraction_role = "_requireSyncInteraction_role-1723203706";
        java.lang.String _requireSyncInteraction_processId = "_requireSyncInteraction_processId-418306075";
        java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> _requireSyncInteraction__return = port.requireSyncInteraction(_requireSyncInteraction_cuiId, _requireSyncInteraction_inputData, _requireSyncInteraction_role, _requireSyncInteraction_processId);
        System.out.println("requireSyncInteraction.result=" + _requireSyncInteraction__return);


        }

        System.exit(0);
    }

}
