package be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-27T15:51:55.126+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "UI-Client", 
                  wsdlLocation = "http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl",
                  targetNamespace = "http://webApp.fundp.ac.be") 
public class UIClient_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webApp.fundp.ac.be", "UI-Client");
    public final static QName UIClientSOAP = new QName("http://webApp.fundp.ac.be", "UI-ClientSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UIClient_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UIClient_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UIClient_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UIClient_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UIClient
     */
    @WebEndpoint(name = "UI-ClientSOAP")
    public UIClient getUIClientSOAP() {
        return super.getPort(UIClientSOAP, UIClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UIClient
     */
    @WebEndpoint(name = "UI-ClientSOAP")
    public UIClient getUIClientSOAP(WebServiceFeature... features) {
        return super.getPort(UIClientSOAP, UIClient.class, features);
    }

}
