
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-27T15:51:55.093+01:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UI-Client",
                      portName = "UI-ClientSOAP",
                      targetNamespace = "http://webApp.fundp.ac.be",
                      wsdlLocation = "http://localhost:8050/WebBrowserAppClient/services/UI-ClientSOAP?wsdl",
                      endpointInterface = "be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.UIClient")
                      
public class UIClientImpl implements UIClient {

    private static final Logger LOG = Logger.getLogger(UIClientImpl.class.getName());

    /* (non-Javadoc)
     * @see be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.UIClient#requireAssyncInteraction(java.lang.String  cuiId ,)java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType>  inputData ,)java.lang.String  role ,)java.lang.String  processId )*
     */
    public void requireAssyncInteraction(java.lang.String cuiId,java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> inputData,java.lang.String role,java.lang.String processId) { 
        LOG.info("Executing operation requireAssyncInteraction");
        System.out.println(cuiId);
        System.out.println(inputData);
        System.out.println(role);
        System.out.println(processId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.UIClient#requireSyncInteraction(java.lang.String  cuiId ,)java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType>  inputData ,)java.lang.String  role ,)java.lang.String  processId )*
     */
    public java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> requireSyncInteraction(java.lang.String cuiId,java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> inputData,java.lang.String role,java.lang.String processId) { 
        LOG.info("Executing operation requireSyncInteraction");
        System.out.println(cuiId);
        System.out.println(inputData);
        System.out.println(role);
        System.out.println(processId);
        try {
            java.util.List<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType> _return = new java.util.ArrayList<be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType>();
            be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType _returnVal1 = new be.ac.fundp.uimanager.dispatcher.soapDispatcher.impl.DataItemType();
            _returnVal1.setDataItemId("DataItemId1680962790");
            _returnVal1.setTypeName("TypeName-853211351");
            java.lang.Object _returnVal1Data = null;
            _returnVal1.setData(_returnVal1Data);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
