<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://process.travel.orgArtifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://fundp.ac.be/UiManager/" name="UIBPEL_ProcessArtifacts" targetNamespace="http://process.travel.orgArtifacts">

    <vprop:property name="processId" type="xsd:string"/>
    <vprop:propertyAlias messageType="xsd1:inputOperationRequest" part="parameters" propertyName="tns:processId">
    <vprop:query><![CDATA[/processId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:inputOperationResponse" part="parameters" propertyName="tns:processId">
    <vprop:query><![CDATA[/processId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:selectionOperationRequest" part="parameters" propertyName="tns:processId">
    <vprop:query><![CDATA[/processId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:selectionOperationResponse" part="parameters" propertyName="tns:processId">
    <vprop:query><![CDATA[/processId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:property name="userIntId" type="xsd:string"/>
    <vprop:propertyAlias messageType="xsd1:inputOperationRequest" part="parameters" propertyName="tns:userIntId">
    <vprop:query><![CDATA[/userInteracId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:inputOperationResponse" part="parameters" propertyName="tns:userIntId">
    <vprop:query><![CDATA[/userInteracId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:selectionOperationRequest" part="parameters" propertyName="tns:userIntId">
    <vprop:query><![CDATA[/userInteracId]]></vprop:query>
  </vprop:propertyAlias>
    <vprop:propertyAlias messageType="xsd1:selectionOperationResponse" part="parameters" propertyName="tns:userIntId">
    <vprop:query><![CDATA[/userInteracId]]></vprop:query>
  </vprop:propertyAlias>
    <import location="UiManager.wsdl" namespace="http://fundp.ac.be/UiManager/"/>
</definitions>
