<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://fundp.ac.be/precise/" nsPrefix="ui_bpel">
  <eClassifiers xsi:type="ecore:EClass" name="UserInteraction" abstract="true" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//BPELExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userRoles" upperBound="-1"
        eType="#//UserRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataInteraction" abstract="true" eSuperTypes="#//UserInteraction ../../org.eclipse.bpel.model/bin/model/bpel.ecore#//ExtensionActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataItem" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//BPELExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../org.eclipse.bpel.model/bin/model/bpel.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="StringType" value="1"/>
    <eLiterals name="IntType" value="2" literal="IntType"/>
    <eLiterals name="DataType" value="3"/>
    <eLiterals name="BooleanType" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataInputUI" eSuperTypes="#//DataInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputItem" upperBound="-1"
        eType="#//DataItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOutputUI" eSuperTypes="#//DataInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputItem" upperBound="-1"
        eType="#//DataItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSelectionUI" eSuperTypes="#//DataInputUI #//DataOutputUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnUserEvent" eSuperTypes="#//UserInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="ecore:EClass ../../org.eclipse.bpel.model/bin/model/bpel.ecore#//Activity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PickUI" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//Pick ../../org.eclipse.bpel.model/bin/model/bpel.ecore#//ExtensionActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInteraction" upperBound="-1"
        eType="#//OnUserEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeUI" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//Scope ../../org.eclipse.bpel.model/bin/model/bpel.ecore#//ExtensionActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventHandlerUI" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//EventHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInteraction" upperBound="-1"
        eType="#//OnUserEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRole" eSuperTypes="../../org.eclipse.bpel.model/bin/model/bpel.ecore#//BPELExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
