//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//


package be.ac.fundp.precise.processDeployment.auiDeployment.codeGenerator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="HOUR"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="NATURAL"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="REAL"/>
 *     &lt;enumeration value="TEXT"/>
 *     &lt;enumeration value="SECRET"/>
 *     &lt;enumeration value="ARRAY"/>
 *     &lt;enumeration value="MULTIMEDIA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(namespace = "http://UsiXML-XSD/AbstractUIModel",
		 name = "DataTypeType")
@XmlEnum
public enum DataTypeType {

    /** The BOOLEAN. */
    BOOLEAN,
    
    /** The HOUR. */
    HOUR,
    
    /** The DATE. */
    DATE,
    
    /** The NATURAL. */
    NATURAL,
    
    /** The INTEGER. */
    INTEGER,
    
    /** The REAL. */
    REAL,
    
    /** The TEXT. */
    TEXT,
    
    /** The SECRET. */
    SECRET,
    
    /** The ARRAY. */
    ARRAY,
    
    /** The MULTIMEDIA. */
    MULTIMEDIA;

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }

    /**
     * From value.
     *
     * @param v the v
     * @return the data type type
     */
    public static DataTypeType fromValue(String v) {
        return valueOf(v);
    }

}
