//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 09:52:26 AM CET 
//


package be.ac.fundp.precise.processDeployment.auiDeployment.codeGenerator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


// TODO: Auto-generated Javadoc
/**
 * <p>Java class for SelectionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SelectionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNDEFINED"/>
 *     &lt;enumeration value="NOSELECTION"/>
 *     &lt;enumeration value="SINGLESELECTION"/>
 *     &lt;enumeration value="SINGLEINTERVAL"/>
 *     &lt;enumeration value="MULTIPLEINTERVAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(namespace = "http://UsiXML-XSD/AbstractUIModel",
		 name = "SelectionType")
@XmlEnum
public enum SelectionType {

    /** The UNDEFINED. */
    UNDEFINED,
    
    /** The NOSELECTION. */
    NOSELECTION,

    /**
     * 
     * 						One item in the list is selectable.
     * 					
     * 
     */
    SINGLESELECTION,

    /**
     * 
     * 						An interval of the list	is selectable.
     * 					
     * 
     */
    SINGLEINTERVAL,

    /**
     * 
     * 						Multiple intervals of the list are selectable.
     * 					
     * 
     */
    MULTIPLEINTERVAL;

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }

    /**
     * From value.
     *
     * @param v the v
     * @return the selection type
     */
    public static SelectionType fromValue(String v) {
        return valueOf(v);
    }

}
