package be.ac.fundp.precise.processDeployment.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-05-08T14:36:31.762+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://precise.funpd.ac.be/AuiDeployer", name = "ProcessDeployer")
@XmlSeeAlso({ObjectFactory.class})
public interface ProcessDeployer {

    @WebResult(name = "deploymentVersion", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
    @RequestWrapper(localName = "deployAui", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer", className = "be.ac.fundp.precise.processDeployment.webService.DeployAui")
    @WebMethod(action = "http://precise.funpd.ac.be/AuiDeployer/deployAui")
    @ResponseWrapper(localName = "deployAuiResponse", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer", className = "be.ac.fundp.precise.processDeployment.webService.DeployAuiResponse")
    public java.lang.String deployAui(
        @WebParam(name = "file", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        byte[] file,
        @WebParam(name = "description", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        java.util.List<be.ac.fundp.precise.processDeployment.webService.AUIDescripton> description,
        @WebParam(name = "processName", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        java.lang.String processName
    );

    @WebResult(name = "deploymentVersion", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
    @RequestWrapper(localName = "deployProcess", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer", className = "be.ac.fundp.precise.processDeployment.webService.DeployProcess")
    @WebMethod(action = "http://precise.funpd.ac.be/AuiDeployer/deployProcess")
    @ResponseWrapper(localName = "deployProcessResponse", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer", className = "be.ac.fundp.precise.processDeployment.webService.DeployProcessResponse")
    public java.lang.String deployProcess(
        @WebParam(name = "auiZip", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        byte[] auiZip,
        @WebParam(name = "processZip", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        byte[] processZip,
        @WebParam(name = "processId", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        java.lang.String processId,
        @WebParam(name = "uiDescription", targetNamespace = "http://precise.funpd.ac.be/AuiDeployer")
        java.util.List<be.ac.fundp.precise.processDeployment.webService.AUIDescripton> uiDescription
    );
}
