
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package be.ac.fundp.precise.processMediation.dataInteraction.webService;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-04-26T17:23:13.990+02:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserEventListener",
                      portName = "UserEventListenerSOAP",
                      targetNamespace = "http://precise.fundp.ac.be/UserEventListener/",
                      wsdlLocation = "http://localhost:8080/ode/processes/UserEventListner?wsdl",
                      endpointInterface = "be.ac.fundp.precise.processMediation.dataInteraction.webService.UserEventListener")
                      
public class UserEventListenerImpl implements UserEventListener {

    private static final Logger LOG = Logger.getLogger(UserEventListenerImpl.class.getName());

    /* (non-Javadoc)
     * @see be.ac.fundp.precise.processMediation.dataInteraction.webService.UserEventListener#fireEvent(java.lang.String  eventId ,)java.lang.String  processId )*
     */
    public void fireEvent(java.lang.String eventId,java.lang.String processId) { 
        LOG.info("Executing operation fireEvent");
        System.out.println(eventId);
        System.out.println(processId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
