
package be.ac.fundp.precise.processMediation.dataInteraction.webService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-04-26T17:23:13.923+02:00
 * Generated source version: 2.5.0
 * 
 */
public final class UserEventListener_UserEventListenerSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://precise.fundp.ac.be/UserEventListener/", "UserEventListener");

    private UserEventListener_UserEventListenerSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserEventListener_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserEventListener_Service ss = new UserEventListener_Service(wsdlURL, SERVICE_NAME);
        UserEventListener port = ss.getUserEventListenerSOAP();  
        
        {
        System.out.println("Invoking fireEvent...");
        java.lang.String _fireEvent_eventId = "_fireEvent_eventId-1333022280";
        java.lang.String _fireEvent_processId = "_fireEvent_processId-982439116";
        port.fireEvent(_fireEvent_eventId, _fireEvent_processId);


        }

        System.exit(0);
    }

}
